# Create a list of my favorite NBA players:
players = [
	'Stephen Curry', 
	'LeBron James', 
	'Kyrie Irving', 
	'Kevin Durant', 
	'Damian Lillard',
	'Anthony Edwards',
	'Jayson Tatum',
	'Jalen Brunson',
	'Jamal Murray',
	'Giannis Antetokounmpo',
	'James Harden',
	'Klay Thompson',
	'Ja Morant',
	'Jimmy Butler III',
	'Luka Dončić',
	'Jaylen Brown',
	'Donovan Mitchell',
	'Kawhi Leonard',
	'Tyler Herro',
	'Russell Westbrook',
	'Trae Young',
	'Cade Cunningham',
	'Shai Gilgeous-Alexander',
	'Nikola Jokić',
	'Paolo Banchero',
	'LaMelo Ball',
	'Anthony Davis',
	'Karl-Anthony Towns',
	'De\'Aaron Fox',
	'DeMar DeRozan',
	'Jordan Poole',
	'Coby White',
	'Tyrese Haliburton'
]
